### ISSUE TITLE
beamcoder on mac

### ISSUE THREAD

**Issue by zWaR** [Streampunk/beamcoder#18]
Hi,

I saw that the documentation mentions macOS support is not there yet. However, is there a way to install and use it manually anyway? Also is there an ETA for official macOS support? We're very interested in beamcoder's capabilities and would like to explore it.

Thanks!

**Comment by sparkpunkd** [comment]
Beamcoder will work on Mac! The installation instructions have been updated but some of the introductory text has not been. I'll do a quick fix on the ReadMe.
