### ISSUE TITLE
AudioInputParam/AudioOutputParam typedefs incorrect

### ISSUE THREAD

**Issue by ccantill** [Streampunk/beamcoder#44]
When setting up a filter, the typedefs specify `channel_layout`, `sample_format` and `sample_rate` properties. However, the implementation seems to expect `channelLayout`, `sampleFormat` and `sampleRate` instead (anything else results in exceptions).

**Comment by scriptorian** [comment]
Hi,
Thanks, I found this error just this week. It should be fixed in 0.5.3.

**Comment by ccantill** [comment]
Woops, sorry :grimacing:  missed that update
