### ISSUE TITLE
Cannot download dev header of ffmpeg on WIndows

### ISSUE THREAD

**Issue by arition** [Streampunk/beamcoder#50]
The ```install_ffmpeg.js``` script will download ```https://ffmpeg.zeranoe.com/builds/win64/dev/ffmpeg-4.2.1-win64-dev.zip``` on windows systems. For now this zip file does not exist on the server (returns a status code of 404).

The website also says that it will stop operating on Sep.18. Maybe we need to find a way to host the binary file.

**Comment by Rock-N-Troll** [comment]
Still not resolved. I came here to see why install wasn't working and I guess this is why based on the timeout. I'll look for a work around in the mean time

**Comment by Rock-N-Troll** [comment]
it looks like getting **full_build-shared.zip** from  **https://www.gyan.dev/ffmpeg/builds/packages/**

As noted on the front-page: "In addition, the release full variant is available as a shared build with development files."

This might be what is needed in the ffmpeg_install.js script for windows.

**Comment by scriptorian** [comment]
Thanks for your patience and determination! This should be working again now, v0.6.1.
