### ISSUE TITLE
flv and rtmp

### ISSUE THREAD

**Issue by felicemarra** [Streampunk/beamcoder#61]
Anyone tried to mux in flv format and stream to rtmp? (like facebook & youtube) 
Any example?

**Comment by Rock-N-Troll** [comment]
Stream to RTP works. This is how I'm currently handling it locally (so it works at least that much).

Once you have a video outputting correctly to a file in flv format, something like this should work when you swap out the video output file:

```
var mux = beamcoder.muxer({ vsync: 0, tune: 'zerolatency', format_name: 'flv', flags: 'low_delay', fflags: 'flush_packets'});

await mux.openIO({
     //url: 'file:testFLV.flv'
     url: 'rtmp://localhost/live/teststream'
});

await mux.writeHeader();
```
