### ISSUE TITLE
How to set movflags?

### ISSUE THREAD

**Issue by felicemarra** [Streampunk/beamcoder#63]
Hi.. I'm trying to stream via rtmp to social networks. 
Everything works with facebook and node-media-stream but I have troubles with youtube and twitch.

I tested with classic ffmpeg and I saw that if I put -movflags faststart works well. If I miss movflags parameter doesn't work. 

So I tried to set movflags with this function 
await muxer.initOutput({ movflags: "faststart" })

but I'm not shure if the syntax is correct. Nothing changes about youtube streaming and I don't know how can I check if this flag is actually setted 

Anyone can help me?

**Comment by Rock-N-Troll** [comment]
If you do a search in this repo, I think you will come across where I found something like the following (mostly untested on my end)

https://github.com/Streampunk/beamcoder/search?q=movflags&type=issues

`await mux.initOutput({ movflags: 'frag_keyframe+empty_moov+default_base_moof'});`
