### ISSUE TITLE
failed to install version v0.7.1

### ISSUE THREAD

**Issue by paulgrammer** [Streampunk/beamcoder#95]
In file included from ../src/beamcoder.cc:23:
../src/beamcoder_util.h:33:12: fatal error: libavutil/error.h: No such file or directory
   33 |   #include <libavutil/error.h>
      |            ^~~~~~~~~~~~~~~~~~~

**Comment by hpaul** [comment]
If anybody stumble upon this error again, it seems like on fedora the headers of `libavutil` are not placed in the right place.

This would do the trick: `cp -r /usr/include/ffmpeg/* /usr/include/`
